services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./model-cache:/root/.cache/llama.cpp
      - ./results:/app/results
      - ./bench-helper.sh:/app/bench-helper.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
